config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :rooms do
    resources :messages
  end

  root to:"login#index",as:"login"

  post "/signin",to: "login#signin"
  post "/signup",to: "login#signup"
  post "/signout",to: "login#signout"
  post "/update_user/:id",to: "profile#update_user",as:"update_user"
  post "/follow",to: "main#follow", as:"follow"
  post "/unfollow",to: "main#unfollow", as:"unfollow"
  #post "/message_create",to: "messages#create", as:"message_create"

  get "/profile/:id",to: "profile#index", as:"profile"
  get "/edit_profile/",to: "profile#edit", as:"edit"
  get "/chat/:id",to: "rooms#show", as:"somebody"
  #get "/room/:id",to: "messages#show", as:"room"
  
  get "/",to: "login#index"
  get "/home",to: "main#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :validate
  before_action :get_current_user
  before_action :friend_params, only: [:follow]

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new

    @users = User.all
    @user = User.new

    @current_user = @users.find_by email: session[:email]
    @friends = @current_user.friends

    unless @current_user.nil?
      @users = User.where.not(id: @current_user.id)
    end
  end

  def follow
    unless @current_user.friends.find_by(friend_params)
      @friend = Friend.new(friend_params)
      @friend.save
    end
    redirect_to home_path
  end

  def get_current_user
    @users = User.all
    @current_user = @users.find_by email: session[:email]
    @current_user
  end

  def validate 
    unless session[:user_id]
      redirect_to login_path
    end
  end

  def unfollow
    if @current_user.friends.find_by(friend_params)
      @friend = Friend.find_by(friend_params)
      @friend.destroy
    end
    redirect_to home_path
  end

  def friend_params
    params.require(:friend).permit(:friend_id, :user_id)
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<div class="main-container">
    <div class="post-container">
        <div class="post-wrapper text-center">
        <div class="post-top">
            <%= form_with(model: @post) do |form| %>
                <%= form.text_area :body,class:"create-post",placeholder:"What's up?",type:"submit"%>
                <button type="submit" class="rounded-circle post-button"><i class="uil uil-angle-left"></i></button>
            <% end %>
            <hr class="text-white"/>
            <h1 class="text-white display-6">Posts </h1>
        </div>
        <% @posts.each do |post|  %>
            <% if @friends.find_by(friend_id: post.user_id) || post.user_id == @current_user.id %>
                <div class="post-content">
                    <div class="post-top">
                        <% if post.user.avatar.attached? %>
                            <%= image_tag(post.user.avatar, :alt => "logo",height:128,width:128,class:"rounded-circle") %>
                        <% else %>
                            <%= image_tag("default.jpg", :alt => "logo",height:128,width:128,class:"rounded-circle") %>
                        <% end %>
                        <h1 style="color:#373f55"><%= post.user.firstname %> <%= post.user.surname %></h1>
                        </div>
                        <div class="post-bottom">
                        <p>
                            <%= render post %>
                        </p>
                    </div>
                    <div class="social mt-2">
                        <% if post.user_id  == @current_user.id%>
                            <%= button_to post, method: :delete  do%> <i class="fa fa-times" aria-hidden="true"></i> <% end %>
                            <%= link_to  edit_post_path(post) do %> <i class="fa fa-pencil"></i><% end %>
                        <% end %>
                        <a href="#"><i class="fa fa-heart" aria-hidden="true"></i> </a>
                    </div>
                </div>
            <% end %>
        <% end %>
        </div>
    </div>
    <div class="friends-container">
        <h1 class="text-white display-6 text-center">Friends</h1>
        <hr class="text-white mb-4"/>
    <% @users.each do |user| %> 
        <div class="friends-wrapper">
            <% if user.avatar.attached?%>
                <%= image_tag(user.avatar, :alt => "logo",height:64,width:64,class:"rounded-circle") %>
            <% else %>
                <%= image_tag("default.jpg", :alt => "logo",height:64,width:64,class:"rounded-circle") %>
            <% end %>
            <%= link_to profile_path(user.id),style:"text-decoration:none" do %><p class="friends-name mt-3"><%= user.firstname %> <%= user.surname %></p><% end %>
            <div>
                <% if @friends.find_by(friend_id: user.id) %>
                    <%= button_to unfollow_path(friend: { friend_id: user.id,user_id: @current_user.id }),method: :post,class:"unfollow-btn text-white" do %> Unfollow <i class="fa fa-check" style="color:#ca6d87"> </i><% end %>
                <% else %>
                    <%= button_to follow_path(friend: { friend_id: user.id,user_id: @current_user.id }),method: :post,class:"follow-btn text-white" do %> Follow <i class="fa fa-check"> </i><% end %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>