config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :rooms do
    resources :messages
  end

  root to:"login#index",as:"login"

  post "/signin",to: "login#signin"
  post "/signup",to: "login#signup"
  post "/signout",to: "login#signout"
  post "/update_user/:id",to: "profile#update_user",as:"update_user"
  post "/follow",to: "main#follow", as:"follow"
  post "/unfollow",to: "main#unfollow", as:"unfollow"
  #post "/message_create",to: "messages#create", as:"message_create"

  get "/profile/:id",to: "profile#index", as:"profile"
  get "/edit_profile/",to: "profile#edit", as:"edit"
  get "/chat/:id",to: "rooms#show", as:"somebody"
  #get "/room/:id",to: "messages#show", as:"room"
  
  get "/",to: "login#index"
  get "/home",to: "main#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaizen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'letter-k.png' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main_page", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "profile_page", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "user_page", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "message_page", "data-turbo-track": "reload" %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
  </head>
  <body>
    <div>
      <div class="side-navbar">
          <ul class="navbar-menu">
            <% unless @current_user.nil? %>
                <%= form_with url: profile_path(@current_user),local:true,method: :get do %>
                  <li class="navbar-item"><a class="fa fa-user "></a><%= submit_tag "Profile",class:"mx-3 button" %></li>
                <% end %>
                <%= form_with url: edit_path,local:true,method: :get do %>
                  <li class="navbar-item"><a class="fa fa-user "></a><%= submit_tag "Edit Profile",class:"button" %></li>
                <% end %>
              <% end %>
              <%= form_with url: rooms_path,local:true,method: :get do %>
                <li class="navbar-item"><a class="fa fa-paper-plane"></a><%= submit_tag "Messages",class:"button" %></li>
              <% end %>
              <%= form_with url: signout_path,local:true,method: :post do %>
                <li class="navbar-item"><a class="fa fa-sign-out"></a><%= submit_tag "Sign out",class:"button mx-2" %></li>
              <% end %>
              
            </ul>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark gradient-custom" id="headerNav">
          <div class="container-fluid justify-content-center mr-5">
                  <%= image_tag("letter-k.png", :alt => "logo",height:64)%>
                  <a class="px-2" href="/home">Kaizen</a>
          </div>
        </nav>
    </div>
      <%= yield %>
    </div>
  </body>
</html>